### ISSUE TITLE
USB devices all connect at USB 2.0 speeds

### ISSUE THREAD

**Issue by jonpage0** [rafaelmaeuer/Asus-Z590-P-Hackintosh#1]
Using this exact hardware configuration and all USB devices connect at USB 2.0 / 480Mbps speeds.

**Comment by rafaelmaeuer** [comment]
Have you done a correct port-mapping? Checkout [OpenCore-Post-Install/usb/intel-mapping](https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html)

**Comment by jonpage0** [comment]
I was under the assumption that the EFI folder already had the USBMap.kext for the Asus Z590-P motherboard. My apologies!

**Comment by rafaelmaeuer** [comment]
Yes it is: https://github.com/rafaelmaeuer/Asus-Z590-P-Hackintosh/tree/master/EFI/OC/Kexts/USBMap.kext, make sure to also inject https://github.com/rafaelmaeuer/Asus-Z590-P-Hackintosh/blob/master/EFI/OC/ACPI/SSDT-USB-Reset.aml

**Comment by rafaelmaeuer** [comment]
should be fixed with f22f8a25f9f8130485f48d463cc9ff4453290fca
